# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogRF.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog,message):
        print('hi')
        Dialog.setObjectName("Dialog")
        Dialog.setStyleSheet("background-color:rgb(245, 222, 179);")
        Dialog.resize(692, 486)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../img/redcrossimage.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(11, 11, 687, 437))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(230, 110, 221, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../img/nurse.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(100, 50, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelPredictResult = QtWidgets.QLabel(self.frame)
        self.labelPredictResult.setGeometry(QtCore.QRect(60, 310, 581, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.labelPredictResult.setFont(font)
        self.labelPredictResult.setStyleSheet("background-color:rgb(170, 85, 127);\n"
"border-style: outset;\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"border-color:black;\n"
"padding:6px;\n"
"min-width:10px;\n"
"color:white\n"
"\n"
"")
        self.labelPredictResult.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPredictResult.setObjectName("labelPredictResult")

        self.retranslateUi(Dialog ,message)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog , message):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Prediction Result"))
        self.label_2.setText(_translate("Dialog", "     Prediction Result with Random Forest"))
        self.labelPredictResult.setText(_translate("Dialog", message))


'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    message = "The patient cannot be readmitted "
    ui.setupUi(Dialog,message)
    Dialog.show()
    sys.exit(app.exec_())'''
